apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 100330/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEQCIED31SuTlqAcDYNP84G97.CvQ0KSgy7r+nIA+2rj8qd3AiAZh6jWUhgrTzgvzKMkjQWzB.Pp2ymCvzX52iplzRTN9w==/ZHU4OmxhdW5jaGVydTQyOjEvOGZhNjk5MDFlMmVmNDI4OGFmOWVmNjJhNDk2NGVhMjNkOTE3ZTI2YnU2OnBsYXllcnU0MjoxL2M5ZmZiYWQ3MGUxNTEwYmJjNDAxOWNmMWQ2Yjc2OTQxNGM4M2I4MDF1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMS0yOGU=
kind: ConfigMap
metadata:
  name: version-config
