apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-us-east-2b
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  zone: us-east-2b
reclaimPolicy: Retain
allowVolumeExpansion: true
