apiVersion: v1
kind: Service
metadata:
  name: svc-headless-query
spec:
  type: LoadBalancer
  selector:
    app: sts-headless-query
  ports:
  - name: graphql
    port: 23061
    targetPort: 23061
  - name: headless
    port: 31234
    targetPort: 31234
