apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: world-boss-service
  name: world-boss-service
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: world-boss-service
  serviceName: world-boss-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: world-boss-service
    spec:
      containers:
        - args:
            - flask --app world_boss/wsgi.py db upgrade --directory world_boss/migrations && gunicorn world_boss.wsgi:app --workers 8 --timeout 600 --bind 0.0.0.0:5000
          command:
            - /bin/sh
            - -c
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: world-boss-env
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: redis-host
                  name: world-boss-env
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: redis-port
                  name: world-boss-env
            - name: KMS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: kms-key-id
                  name: world-boss-env
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  key: slack-token
                  name: world-boss-env
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: celery-broker-url
                  name: world-boss-env
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: celery-result-backend
                  name: world-boss-env
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  key: slack-signing-secret
                  name: world-boss-env
          image: planetariumhq/world-boss-service:git-e6f45eaaeec08a66a0a5b3b6a0123aca4fd8570a
          name: world-boss-service
          ports:
            - containerPort: 5000
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      serviceAccount: aws-iam-role
      serviceAccountName: aws-iam-role
  updateStrategy:
    type: OnDelete
