apiVersion: v1
kind: Service
metadata:
  name: network-tcp
spec:
  ports:
  - name: node
    port: 31236
    targetPort: 31236
  - name: graphql
    port: 31237
    targetPort: 31237
  selector:
    app: previewnet-seed-tcp
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: network
spec:
  ports:
  - name: node
    port: 31236
    targetPort: 31236
  - name: graphql
    port: 31237
    targetPort: 31237
  selector:
    app: previewnet-seed
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: rpc
spec:
  ports:
  - port: 31233
    targetPort: 31233
  selector:
    app: previewnet-seed
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: explorer
spec:
  ports:
  - port: 31235
    targetPort: 31235
  selector:
    app: explorer
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: bridge-api-node
spec:
  clusterIP: None
  ports:
  - port: 31235
    name: graphql
    targetPort: 31235
  selector:
    app: bridge-api-node

---

apiVersion: v1
kind: Service
metadata:
  name: previewnet-auth-miner
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  selector:
    app: previewnet-auth-miner
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: previewnet-miner-1
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  selector:
    app: previewnet-miner-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: previewnet-miner-2
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  selector:
    app: previewnet-miner-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-1
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-1
  type: LoadBalancer
