apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: client
    name: client
  spec:
    progressDeadlineSeconds: 600
    replicas: 0
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: client
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: client
      spec:
        containers:
        - command:
          - /entrypoint.sh
          - --no-miner
          - --development
          - --auto-play
          - --console-sink
          - --ice-servers=turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@15.165.103.105:3478
          - --peer
          - <seed-address>,<endpoint>,31234
          image: <image-name>
          imagePullPolicy: IfNotPresent
          name: client
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: acr-regcred
        nodeSelector:
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
