apiVersion: v1
kind: Service
metadata:
  name: network
spec:
  ports:
  - port: 31234
    targetPort: 31234
  selector:
    app: seed
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: rpc
spec:
  ports:
  - port: 31233
    targetPort: 31233
  selector:
    app: seed
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: explorer
spec:
  ports:
  - port: 31235
    targetPort: 31235
  selector:
    app: explorer
  type: LoadBalancer
