apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: seed-1-data-seed-1-0
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared
      mountPath: /data
  hostNetwork: true
  dnsPolicy: Default
