apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test-miner-1
  name: test-miner-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-miner-1
  serviceName: test-miner-1
  template:
    metadata:
      labels:
        app: test-miner-1
        tags.datadoghq.com/env: test-miner-1
        tags.datadoghq.com/version: '1'
      name: test-miner-1
    spec:
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --workers=1000
        - --app-protocol-version=1067/8c72600A23ed14026ab76d56B9A0edc339B305B0/MEUCIQDBsAhBgWjwg91M9miBpA+XjX2hQMdk8PvGa9ZN8QsskgIgJ73BV+Y0Lj+8aXZH.S36KC2tO2CdxdTOnMw6OvWbuHc=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTY1Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS9wcmV2aWV3bmV0L3YxMDY3L1dpbmRvd3MuemlwdTk6dGltZXN0YW1wdTEwOjIwMjItMDYtMTZl
        - --trusted-app-protocol-version-signer=02182d2d97a0cbc56c84b3eff293ca3aadc3baab6e3bc1359c0c93d0ab4eb0d1d9
        - --genesis-block-path=https://drfoj4ogb5dwf.cloudfront.net/genesis-block-9c-test
        - --host=ad9d58117b71f4677a87bee061c1b8e7-1791310159.us-east-2.elb.amazonaws.com
        - --port=31234
        - --store-path=/data/miner
        - --store-type=rocksdb
        - --swarm-private-key
        - $(PRIVATE_KEY)
        - --miner-private-key
        - $(PRIVATE_KEY)
        - --peer=0304a8eafaf5a51c52d47446b73e03819f46704ec6452cfa33c4bcd35595a0a2a1,a8b2d3c50319a4a78873aefcdbbc0e0a-281872577.us-east-2.elb.amazonaws.com,31234
        - --graphql-server
        - --graphql-host=0.0.0.0
        - --graphql-port=80
        - --network-type=default
        command:
          - dotnet
        env:
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: miner1
              name: miner-keys
        image: planetariumhq/ninechronicles-headless:git-051ba506e1c32c10699ebd2bbc7ec04b8e979829
        imagePullPolicy: IfNotPresent
        name: test-miner-1
        ports:
        - containerPort: 31234
          name: headless
          protocol: TCP
        - containerPort: 80
          name: graphql
          protocol: TCP
        resources:
          requests:
            cpu: 2
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: test-miner-1-data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: test-miner-1-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Gi
      storageClassName: gp2-extensible
      volumeMode: Filesystem
---
