apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: onboarding-app
  name: onboarding-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: onboarding-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/onboarding-net: "true"
        io.kompose.service: onboarding-app
    spec:
      containers:
        - args:
            - ./wait-for-postgres.sh $(DB_HOST) 5432 $(DB_USER) $(DB_PASS) && ./migrate.sh /app/data/migrations && gunicorn app:app --workers 8 --timeout 600 --bind 0.0.0.0:5000
          command:
            - /bin/sh
            - -c
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws-access-key-id
                  name: onboarding-env
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: aws-default-region
                  name: onboarding-env
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws-secret-access-key
                  name: onboarding-env
            - name: CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: consumer-key
                  name: onboarding-env
            - name: CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: consumer-secret
                  name: onboarding-env
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: onboarding-env
            - name: DATA_PROVIDER_URL
              value: http://a415209f3ae5c452c989925283550f4b-800556987.us-east-2.elb.amazonaws.com/graphql
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db-host
                  name: onboarding-env
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db-name
                  name: onboarding-env
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: db-pass
                  name: onboarding-env
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: onboarding-env
            - name: HEADLESS_URL_FOR_QUERY
              value: http://ade6401140126484caf2be16360c6703-517332653.us-east-2.elb.amazonaws.com/graphql
            - name: HEADLESS_URL_FOR_TRANSFER
              value: http://ade6401140126484caf2be16360c6703-517332653.us-east-2.elb.amazonaws.com/graphql
            - name: REDIS_HOST
              value: acb87a9b2ec3e44cfbdfc36dbb9f7ef3-77478302.us-east-2.elb.amazonaws.com
            - name: REDIS_PORT
              value: "6379"
            - name: KMS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: kms-key-id
                  name: onboarding-env
            - name: NC_ADDRESS
              value: 0x17f3786dffc6D47767f4f4954F9fD8bb6AADf095
            - name: QUIZ_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  key: quiz-auth-key
                  name: onboarding-env
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: recaptcha-secret-key
                  name: onboarding-env
            - name: RECAPTCHA_SITE_KEY
              valueFrom:
                secretKeyRef:
                  key: recaptcha-site-key
                  name: onboarding-env
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: onboarding-env
            - name: WEB3_INFURA_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: web3-infura-api-secret
                  name: onboarding-env
            - name: WEB3_INFURA_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: web3-infura-project-id
                  name: onboarding-env
          image: planetariumhq/9c-onboarding:git-87e7dc67cc68318bb5fbdb99c648fdb9555c5a04
          name: onboarding-app
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred          
      
status: {}
