apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: onboarding-db
  name: onboarding-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: onboarding-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/onboarding-net: "true"
        io.kompose.service: onboarding-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: reward_withdrawal
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13.3
          name: onboarding-db
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
