apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: onboarding-redis
  name: onboarding-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: onboarding-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/onboarding-net: "true"
        io.kompose.service: onboarding-redis
    spec:
      containers:
        - args:
            - redis-server
            - --appendonly
            - "yes"
          image: redis:6.2
          name: onboarding-redis
          ports:
            - containerPort: 6379
