apiVersion: v1
kind: Service
metadata:
  name: test-tcp-seed-1
spec:
  ports:
  - port: 31234
    targetPort: 31234
  selector:
    app: test-tcp-seed-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: test-miner-1
spec:
  ports:
  - port: 31234
    targetPort: 31234
    name: headless
  - port: 80
    targetPort: 80
    name: gql
  selector:
    app: test-miner-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: test-data-provider
spec:
  ports:
  - name: headless
    port: 31234
    targetPort: 31234
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: test-data-provider
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-1
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-2
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: onboarding-redis
  name: onboarding-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: onboarding-redis
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: onboarding-db
  name: onboarding-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: onboarding-db
  type: LoadBalancer


---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: onboarding-app
  name: onboarding-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 5000
  selector:
    io.kompose.service: onboarding-app
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: faucet-front
  name: faucet-front
spec:
  ports:
    - name: 3000-tcp
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: faucet-front
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: faucet-backend
  name: faucet-backend
spec:
  ports:
    - name: 8002-tcp
      port: 8002
      targetPort: 8002
  selector:
    io.kompose.service: faucet-backend
  type: LoadBalancer
