apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    app: ninechronicles-headless-metrics-aggregator
  name: ninechronicles-headless-metrics-aggregator
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ninechronicles-headless-metrics-aggregator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ninechronicles-headless-metrics-aggregator
    spec:
      containers:
      - image: planetariumhq/ninechronicles-headless-metrics-aggregator:git-13ee4944967526a98d5256fa669cf41d00f7d453
        imagePullPolicy: IfNotPresent
        command:
          - poetry
          - run
          - uvicorn
          - app:app
          - --port=80
          - --host=0.0.0.0
          - --log-level=trace
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        name: ninechronicles-headless-metrics-aggregator
        ports:
        - containerPort: 80
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: "0.4"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: ninechronicles-headless-metrics-aggregator
spec:
  ports:
  - name: metrics
    port: 80
    targetPort: 80
  selector:
    app: ninechronicles-headless-metrics-aggregator
