serviceAccounts:
  alertmanager:
    create: false
    name:
    annotations: {}
  nodeExporter:
    create: false
    name:
    annotations: {}
  pushgateway:
    create: false
    name:
    annotations: {}
  server:
    create: true
    name:
    annotations: {}

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

server:
  enabled: true
  persistentVolume:
    storageClass: gp2-extensible
  retention: "90d"

serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
      ## Below two files are DEPRECATED will be removed from this default values file
      - /etc/config/rules
      - /etc/config/alerts
    
    scrape_configs:
      - job_name: ninechronicles-headless-metrics-aggregator
        metrics_path: /metrics
        scrape_interval: 5m
        scrape_timeout: 5m
        static_configs:
          - targets:
            - ninechronicles-headless-metrics-aggregator.monitoring.svc.cluster.local:80
        tls_config:
          insecure_skip_verify: true
