apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: miner
    name: miner
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: miner
    serviceName: miner
    template:
      metadata:
        labels:
          app: miner
      spec:
        initContainers:
        - name: reset-snapshot
          image: mcr.microsoft.com/powershell:latest
          command:
          - pwsh
          args: ["/data/download-snapshot.ps1", "https://snapshots.nine-chronicles.com/audit/", "/data/miner"]
          volumeMounts:
          - name: miner-data
            mountPath: /data
          - name: download-snapshot
            mountPath: /data/download-snapshot.ps1
            subPath: download-snapshot.ps1
        containers:
        - args:
          - NineChronicles.Headless.Executable.dll
          - run
          - --workers=50
          - --app-protocol-version=1001/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIAjbjI66neIHY9kFStJCmvOE6vuXotan3BLEzuf08V74AiBbHunUaX6VNNBiPaTUHY1TPLOMdzQkwUl0xKAYwzjxnw==/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU0Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMS9XaW5kb3dzLnppcHU5OnRpbWVzdGFtcHUxMDoyMDIxLTA4LTA1ZQ==
          - --trusted-app-protocol-version-signer=02529a61b9002ba8f21c858224234af971e962cac9bd7e6b365e71e125c6463478
          - --genesis-block-path=https://release.nine-chronicles.com/genesis-block-9c-main
          - --store-path=/data/miner
          - --store-type=rocksdb
          - --ice-server=turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn.planetarium.dev:3478/
          - --peer
          - 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,a57000af8397d4774b279f1fe09eccce-332461311.ap-northeast-2.elb.amazonaws.com,31236
          - --miner-private-key
          - "$(PRIVATE_KEY)"
          - --graphql-server
          - --graphql-port=80
          command:
          - dotnet
          image: planetariumhq/ninechronicles-headless:git-e437c0ab166320493d0e1e948e0118ec1e1ba679
          imagePullPolicy: IfNotPresent
          env:
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: miner-keys
                  key: miner1
          name: miner
          ports:
          - containerPort: 80
            name: graphql
            protocol: TCP
          resources:
            requests:
              cpu: 1500m
              memory: 6Gi
            limits:
              memory:
                6Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: miner-data
        dnsPolicy: ClusterFirst
        nodeSelector:
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: download-snapshot
          configMap:
            name: scripts
            items:
              - key: download-snapshot.ps1
                path: download-snapshot.ps1
    updateStrategy:
      type: OnDelete
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: miner-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            cpu: 1500m
            memory: 6Gi
            storage: 20Gi
          limits:
            memory:
              6Gi
        storageClassName: gp2-extensible
        volumeMode: Filesystem
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: auth-miner
    name: auth-miner
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: auth-miner
    serviceName: auth-miner
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: auth-miner
      spec:
        initContainers:
        - name: reset-snapshot
          image: mcr.microsoft.com/powershell:latest
          command:
          - pwsh
          args: ["/data/download-snapshot.ps1", "https://snapshots.nine-chronicles.com/audit/", "/data/miner"]
          volumeMounts:
          - name: auth-miner-data
            mountPath: /data
          - name: download-snapshot
            mountPath: /data/download-snapshot.ps1
            subPath: download-snapshot.ps1
        containers:
        - args:
          - NineChronicles.Headless.Executable.dll
          - run
          - --workers=50
          - --app-protocol-version=1001/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIAjbjI66neIHY9kFStJCmvOE6vuXotan3BLEzuf08V74AiBbHunUaX6VNNBiPaTUHY1TPLOMdzQkwUl0xKAYwzjxnw==/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU0Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMS9XaW5kb3dzLnppcHU5OnRpbWVzdGFtcHUxMDoyMDIxLTA4LTA1ZQ==
          - --trusted-app-protocol-version-signer=02529a61b9002ba8f21c858224234af971e962cac9bd7e6b365e71e125c6463478
          - --genesis-block-path=https://release.nine-chronicles.com/genesis-block-9c-main
          - --store-path=/data/miner
          - --store-type=rocksdb
          - --ice-server=turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn.planetarium.dev:3478/
          - --peer
          - 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,a57000af8397d4774b279f1fe09eccce-332461311.ap-northeast-2.elb.amazonaws.com,31236
          - --miner-private-key
          - "$(PRIVATE_KEY)"
          - --authorized-miner
          command:
          - dotnet
          image: planetariumhq/ninechronicles-headless:git-e437c0ab166320493d0e1e948e0118ec1e1ba679
          imagePullPolicy: IfNotPresent
          env:
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: miner-keys
                  key: miner2
          name: auth-miner
          resources:
            requests:
              cpu: 1500m
              memory: 6Gi
            limits:
              memory:
                6Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: auth-miner-data
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: acr-regcred
        nodeSelector:
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: download-snapshot
          configMap:
            name: scripts
            items:
              - key: download-snapshot.ps1
                path: download-snapshot.ps1
    updateStrategy:
      type: OnDelete
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: auth-miner-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            cpu: 1500m
            memory: 6Gi
            storage: 20Gi
          limits:
            memory:
              6Gi
        storageClassName: gp2-extensible
        volumeMode: Filesystem
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: explorer
    name: explorer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: explorer
    serviceName: explorer
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: explorer
      spec:
        initContainers:
        - name: reset-snapshot
          image: mcr.microsoft.com/powershell:latest
          command:
          - pwsh
          args: ["/data/download-snapshot.ps1", "https://snapshots.nine-chronicles.com/audit/", "/data/explorer"]
          volumeMounts:
          - name: explorer-data
            mountPath: /data
          - name: download-snapshot
            mountPath: /data/download-snapshot.ps1
            subPath: download-snapshot.ps1
        containers:
        - command:
          - ./Libplanet.Explorer.Executable
          - -p 31235
          - -d
          - -s
          - 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,a57000af8397d4774b279f1fe09eccce-332461311.ap-northeast-2.elb.amazonaws.com,31236
          - -I
          - turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn.planetarium.dev:3478/
          - -i 8000
          - -m 100000
          - -D 2048
          - -G https://release.nine-chronicles.com/genesis-block-9c-main
          - -V 1001/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIAjbjI66neIHY9kFStJCmvOE6vuXotan3BLEzuf08V74AiBbHunUaX6VNNBiPaTUHY1TPLOMdzQkwUl0xKAYwzjxnw==/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU0Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMS9XaW5kb3dzLnppcHU5OnRpbWVzdGFtcHUxMDoyMDIxLTA4LTA1ZQ==
          - "--max-genesis-bytes"
          - "15728640"
          - -T
          - rocksdb
          - -P
          - /data/explorer
          image: planetariumhq/libplanet-explorer:git-2544f86eb2738fde0ee561e2657590945227d2bc
          imagePullPolicy: IfNotPresent
          name: explorer-test
          ports:
          - containerPort: 31235
            name: explorer
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: explorer-data
        dnsPolicy: ClusterFirst
        nodeSelector:
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: download-snapshot
          configMap:
            name: scripts
            items:
              - key: download-snapshot.ps1
                path: download-snapshot.ps1
    volumeClaimTemplates:
    - metadata:
        name: explorer-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
        volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
