apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1109/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCID0VxfMcT6fnmc+K8++VTUHI6ZwhK.jEKZHvhApjQ8CRAiBABXOJVRi7RzygqxrFeSMsoZS8Ap9k3.SIKInHsQLi4Q==/ZHU4OmxhdW5jaGVydTQyOjEvMzI5NjYyZGYyMjM3YzA4YzNkYTEzNmMxNDk0NTM1NzA4NGQ3MzgxZXU2OnBsYXllcnU0MjoxLzhiM2IxNWRjMTBiNjViZjY2MmQ3YjhiNTFjYWM0MjA4YmRiODVmMTF1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMC0xNGU=
kind: ConfigMap
metadata:
  name: version-config
