apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1111/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIEdwqmO6UfeR.7Vww5buxF.kzdD+NP9rHefIxSPK8DWKAiBedRyPQ2B9dV9ZVFi.3bbwISj8hjOhSUG5uFJVsOubSg==/ZHU4OmxhdW5jaGVydTQyOjEvMzI5NjYyZGYyMjM3YzA4YzNkYTEzNmMxNDk0NTM1NzA4NGQ3MzgxZXU2OnBsYXllcnU0MjoxLzhiM2IxNWRjMTBiNjViZjY2MmQ3YjhiNTFjYWM0MjA4YmRiODVmMTF1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMC0xNGU=
kind: ConfigMap
metadata:
  name: version-config
