apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1117/54684Ac4ee5B933e72144C4968BEa26056880d71/MEUCIQCBRWRGcgzxqDnuuPYh.RRpqRpzzp4FM8Mz0kxcrQXnnAIgM7kD3pfTtcYtVdffn9EMV8BNjvUOqGUzbEMp57aoYG4=/ZHU4OmxhdW5jaGVydTQyOjEvNGQwNTNjYWIzODdhNmQ4NWQ3MGFkYmRmMTcwYjEwOTI3ZTE1MDcxOHU2OnBsYXllcnU0MjoxL2EzZTNlOTRlOTAzY2FhODE0M2JlYzRjZmI1ZjZmNDhhYTdjNWViMjh1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMC0xN2U=
kind: ConfigMap
metadata:
  name: version-config
