images:
- name: kustomization-libplanet-seed
  newName: planetariumhq/libplanet-seed
  newTag: git-4d10b228048c03cc97a6fbb7fbfcd54d2bd1b21c
- name: kustomization-ninechronicles-headless
  newName: planetariumhq/ninechronicles-headless
  newTag: git-ba3c2e15cb75a9856a8000e3e7e67e33efb8d6c7
- name: kustomization-ninechronicles-snapshot
  newName: planetariumhq/ninechronicles-snapshot
  newTag: git-ffb78149efb29d893d4460b4f9a70260c6b340f3
- name: kustomization-ninechronicles-dataprovider
  newName: planetariumhq/ninechronicles-dataprovider
  newTag: git-63ddf79fbe3d4287b25c3efca9c67ff3c7dfebc4
- name: kustomization-ninechronicles-onboarding
  newName: planetariumhq/9c-onboarding
  newTag: git-36b2b5ca12e6bd059a81c17f92cb2803b38425bc
resources:
- explorer.yaml
- miner-1.yaml
- remote-headless-1.yaml
- data-provider.yaml
- data-provider-db.yaml
- onboarding-app.yaml
- onboarding-db.yaml
- onboarding-redis.yaml
- snapshot.yaml
- tcp-seed-deployment.yaml
