apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: internal-onboarding-redis
  name: internal-onboarding-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-onboarding-redis
  serviceName: internal-onboarding-redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: internal-onboarding-redis
    spec:
      containers:
        - args:
            - redis-server
            - --appendonly
            - "yes"
          image: redis:6.2
          name: internal-onboarding-redis
          ports:
            - containerPort: 6379
