apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-extensible
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-extensible-us-east-2c
parameters:
  fsType: ext4
  type: gp2
  zone: "us-east-2c"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
