apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: headless-admin
  name: headless-admin
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: headless-admin
  serviceName: headless-admin
  template:
    metadata:
      labels:
        app: headless-admin
    spec:
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --app-protocol-version=$(APP_PROTOCOL_VERSION_KEY)
        - --store-path=/data/headless
        - --swarm-private-key
        - $(PRIVATE_KEY)
        - --miner-private-key
        - $(PRIVATE_KEY)
        - --graphql-server
        - --graphql-host=0.0.0.0
        - --graphql-port=80
        - --chain-tip-stale-behavior-type=reboot
        - --no-cors
        - --config-path=https://9c-dev-cluster-configs.s3.ap-northeast-2.amazonaws.com/9c-pbft-internal-2.headless.appsettings.json
        command:
        - dotnet
        image: kustomization-ninechronicles-headless
        imagePullPolicy: IfNotPresent
        env:
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: headless-keys
              key: headless-admin
        - name: APP_PROTOCOL_VERSION_KEY
          valueFrom:
            configMapKeyRef:
              name: version-config
              key: APP_PROTOCOL_VERSION
        name: headless-admin
        ports:
        - containerPort: 80
          name: graphql
          protocol: TCP
        - containerPort: 31234
          name: headless
          protocol: TCP
        - containerPort: 31238
          name: rpc
          protocol: TCP
        resources:
          requests:
            cpu: 1300m
            memory: 5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: headless-admin-data
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - https://9c-snapshot-dev.s3.us-east-2.amazonaws.com/9c-pbft-internal
        - /data/headless
        - $(RESET_SNAPSHOT_OPTION)
        - headless-admin
        - $(SLACK_TOKEN)
        command:
        - /bin/download_snapshot.sh
        image: bash:latest
        name: reset-snapshot
        volumeMounts:
        - name: script-volume
          mountPath: /bin/download_snapshot.sh
          readOnly: true
          subPath: download_snapshot.sh
        - mountPath: /data
          name: headless-admin-data
        env:
        - name: RESET_SNAPSHOT_OPTION
          valueFrom:
            configMapKeyRef:
              name: reset-snapshot-option
              key: RESET_SNAPSHOT_OPTION
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack
              key: token
      - args:
        - sleep 60
        command:
        - /bin/sh
        - -c
        image: nginx
        name: wait-for-miner
      restartPolicy: Always
      volumes:
      - name: script-volume
        configMap:
          defaultMode: 0700
          name: snapshot-script
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: headless-admin-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: gp2-extensible-us-east-2b
      volumeMode: Filesystem
