images:
- name: kustomization-libplanet-seed
  newName: planetariumhq/libplanet-seed
  newTag: git-d52f80f561bf22066fb7555db829f7d262fdece6
- name: kustomization-ninechronicles-headless
  newName: planetariumhq/ninechronicles-headless
  newTag: git-e3be224290311b770b593a159c88682446acddb9 
- name: kustomization-ninechronicles-dataprovider
  newName: planetariumhq/ninechronicles-dataprovider
  newTag: git-d932d9a717616f02f78845e67df628863b84aaf3
resources:
 - explorer.yaml
 - validator-1.yaml
 - validator-2.yaml
 - validator-3.yaml
 - validator-4.yaml
 - validator-5.yaml
 - validator-6.yaml
 - validator-7.yaml
 - validator-8.yaml
 - validator-9.yaml
 - validator-10.yaml
 - validator-11.yaml
 - validator-12.yaml
 - remote-headless-1.yaml
 - tcp-seed-deployment.yaml
