apiVersion: v1
data:
  miner1: <key>
  miner2: <key>
kind: Secret
metadata:
  name: miner-keys
  namespace: default
type: Opaque

---

apiVersion: v1
data:
  seed1: <key>
kind: Secret
metadata:
  name: seed-keys
  namespace: default
type: Opaque

---

apiVersion: v1
data:
  token: <token>
kind: Secret
metadata:
  name: slack
  namespace: default
type: Opaque


