apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2-extensible-us-east-2c
  volumeMode: Filesystem
