apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 100370/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEUCIQDOKrAvKTmsTu8.TQhofFya9CeW8tQY8sLLDj6F3U2DigIgJSSLMRPvs3BIvll7ZoBaa6yD8Ryn3nCr1Ohy0qfwphY=/ZHU4OmxhdW5jaGVydTQyOjEvNTk1OTY0OWE3NTE5NWE3YTUzYzU2Nzk0NmU3ZTVhZWRiMjFhYTU3ZXU2OnBsYXllcnU0MjoxLzQ0YzEyMDllY2FhZDE5YjQzNWYzN2E2MjM3OTQ2ZGUwNjNjMGNjZWF1OTp0aW1lc3RhbXB1MTA6MjAyMy0wMy0wMmU=
kind: ConfigMap
metadata:
  name: version-config
