apiVersion: v1
kind: ConfigMap
metadata:
  name: probe-script
data:
  liveness_probe.sh: |-
    #!/usr/bin/env bash
    set -ex

    preloaded="$(
      curl \
        -H 'Content-Type: application/json' \
        --data '{"query":"query{nodeStatus{preloadEnded}}"}' \
        http://localhost:80/graphql \
      | jq .data.nodeStatus.preloadEnded
    )"

    echo $preloaded
    if [[ "$preloaded" = "true" ]]; then
      echo "Preload finished. Check chain tip."
      local_tip="$(
        curl \
          -H 'Content-Type: application/json' \
          --data '{"query":"query{chainQuery{blockQuery{blocks(desc:true,limit:1){index}}}}"}' \
          http://localhost:80/graphql \
        | jq -r '.data.chainQuery.blockQuery.blocks[0].index'
      )"
      miner_tip="$(
        curl \
          -H 'Content-Type: application/json' \
          --data '{"query":"query{chainQuery{blockQuery{blocks(desc:true,limit:1){index}}}}"}' \
          http://9c-miner.planetarium.dev/graphql \
        | jq -r '.data.chainQuery.blockQuery.blocks[0].index'
      )"
      [[ $(( miner_tip - local_tip)) -gt 20 ]]
    fi
  readiness_probe.sh: |-
    #!/usr/bin/env bash
    set -ex

    preloaded="$(
      curl \
        -H 'Content-Type: application/json' \
        --data '{"query":"query{nodeStatus{preloadEnded}}"}' \
        http://localhost:80/graphql \
      | jq .data.nodeStatus.preloadEnded
    )"
    [[ "$preloaded" = "true" ]]
