apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: main-data-provider
  name: main-data-provider
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: main-data-provider
  serviceName: main-data-provider
  template:
    metadata:
      labels:
        app: main-data-provider
    spec:
      containers:
      - args:
        - NineChronicles.DataProvider.Executable.dll
        command:
        - dotnet
        env:
        - name: NC_StorePath
          value: /data/data-provider
        - name: NC_AppProtocolVersionToken
          value: 100291/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCA3lzUAt0QBfG.+ezw4CQ69zBy669sANEt5juSJgzqcgIgbozfpcyeuKJDeJoT5exyGYDYBqCpxklsMEfs0SQ6qzo=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTcyOmh0dHBzOi8vcmVsZWFzZS5uaW5lLWNocm9uaWNsZXMuY29tL21haW4vdjEwMDI5MS9sYXVuY2hlci92MS9XaW5kb3dzLnppcHU5OnRpbWVzdGFtcHUxMDoyMDIyLTA5LTA3ZQ==
        - name: NC_Confirmations
          value: '0'
        - name: NC_PeerStrings__0
          value: 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234
        - name: NC_PeerStrings__1
          value: 02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234
        - name: NC_PeerStrings__2
          value: 0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234
        - name: NC_Preload
          value: 'true'
        - name: NC_Render
          value: 'false'
        - name: NC_MySqlConnectionString
          valueFrom:
            secretKeyRef:
              key: value
              name: data-provider-conn
        image: planetariumhq/ninechronicles-dataprovider:git-9ef64c37f9ebee8953be6de722eb639bf9bf263c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "set -e\nlast_block=\"$(\n  curl \\\n    -H 'Content-Type: application/json'\
              \ \\\n    --data '{\"query\":\"query{chainQuery{blockQuery{blocks(desc:true,limit:1){timestamp}}}}\"\
              }' \\\n    http://localhost:80/graphql_headless \\\n  | jq -r '.data.chainQuery.blockQuery.blocks[0].timestamp'\n\
              )\"\nlast_timestamp=\"$(date +%s -u --date=\"$last_block\")\"\nnow=\"\
              $(date +%s -u)\"\n[[ $(( now - last_timestamp )) -lt 900 ]]\n"
          failureThreshold: 3
          initialDelaySeconds: 1800
          periodSeconds: 30
          timeoutSeconds: 30
        name: main-data-provider
        ports:
        - containerPort: 80
          name: graphql
          protocol: TCP
        resources:
          requests:
            cpu: 1300m
            memory: 7Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: main-data-provider-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: 9c-main-2xl
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: main-data-provider-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1000Gi
      storageClassName: gp2-extensible-us-east-2b
      volumeMode: Filesystem
