apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main-seed-2
  name: main-seed-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-seed-2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: main-seed-2
    spec:
      containers:
      - args:
        - Libplanet.Seed.Executable.dll
        - run
        - --log-level=debug
        - --app-protocol-version=100302/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCiXJnTqI.XvSOo.YbjR13jespoTcLnv25Mf6KmoYomlwIgZKFqAChtennyviPM.TLFgsjZCwu9gM.wpN78.nMN7Us=/ZHU4OmxhdW5jaGVydTQyOjEvNTBkYTNhZjNlYmM3OGFlN2ZjMGZiOTFlY2M4MzM5ZmQ0MGQxYTkyZXU2OnBsYXllcnU0MjoxLzc4MWVkMTQ0YWJlYTQ4MmU1ODFkNjM5MWIwNDUyMzI5MmU3MzI2NjF1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMC0wNGU=
        - --host=9c-main-seed-2.planetarium.dev
        - --port=31234
        - --private-key=$(SEED_PRIVATE_KEY)
        - --graphql-host=0.0.0.0
        - --graphql-port=31237
        - --workers=500
        command:
        - dotnet
        image: planetariumhq/libplanet-seed:git-4d10b228048c03cc97a6fbb7fbfcd54d2bd1b21c
        imagePullPolicy: IfNotPresent
        env:
        - name: SEED_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: seed2
              name: seed-keys
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 31234
          timeoutSeconds: 1
        name: main-seed-2
        ports:
        - containerPort: 31234
          name: node
          protocol: TCP
        - containerPort: 31237
          name: graphql
          protocol: TCP
        resources:
          requests:
            cpu: '1'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: 9c-main-xl
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
