apiVersion: v1
kind: Service
metadata:
  name: main-tcp-seed-1
spec:
  ports:
  - name: node
    port: 31234
    targetPort: 31234
  - name: graphql
    port: 31237
    targetPort: 31237
  selector:
    app: main-tcp-seed-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-tcp-seed-2
spec:
  ports:
  - name: node
    port: 31234
    targetPort: 31234
  - name: graphql
    port: 31237
    targetPort: 31237
  selector:
    app: main-tcp-seed-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-tcp-seed-3
spec:
  ports:
  - name: node
    port: 31234
    targetPort: 31234
  - name: graphql
    port: 31237
    targetPort: 31237
  selector:
    app: main-tcp-seed-3
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-miner-1
spec:
  ports:
  - port: 31234
    targetPort: 31234
    name: headless
  - port: 80
    targetPort: 80
    name: gql
  selector:
    app: main-miner-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-miner-2
spec:
  ports:
  - port: 31234
    targetPort: 31234
    name: headless
  - port: 80
    targetPort: 80
    name: gql
  selector:
    app: main-miner-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-miner-3
spec:
  ports:
  - port: 31234
    targetPort: 31234
    name: headless
  - port: 80
    targetPort: 80
    name: gql
  selector:
    app: main-miner-3
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-miner-4
spec:
  ports:
  - port: 31234
    targetPort: 31234
    name: headless
  - port: 80
    targetPort: 80
    name: gql
  selector:
    app: main-miner-4
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: explorer
spec:
  ports:
  - port: 31235
    targetPort: 31235
  selector:
    app: explorer
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-full-state
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: main-full-state
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-data-provider
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: main-data-provider
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: main-data-provider-db
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  selector:
    app: main-data-provider-db
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-1
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-2
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-3
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-3
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-4
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-4
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-5
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-5
  type: LoadBalancer
