apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot-partition
  namespace: default
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - args:
            - 100291/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCA3lzUAt0QBfG.+ezw4CQ69zBy669sANEt5juSJgzqcgIgbozfpcyeuKJDeJoT5exyGYDYBqCpxklsMEfs0SQ6qzo=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTcyOmh0dHBzOi8vcmVsZWFzZS5uaW5lLWNocm9uaWNsZXMuY29tL21haW4vdjEwMDI5MS9sYXVuY2hlci92MS9XaW5kb3dzLnppcHU5OnRpbWVzdGFtcHUxMDoyMDIyLTA5LTA3ZQ==
            - $(SLACK_TOKEN)
            - $(CF_DISTRIBUTION_ID)
            command:
            - /bin/upload_snapshot.sh
            image: planetariumhq/ninechronicles-snapshot:git-ffb78149efb29d893d4460b4f9a70260c6b340f3
            name: upload-snapshot
            volumeMounts:
            - mountPath: /bin/upload_snapshot.sh
              name: snapshot-script-partition
              readOnly: true
              subPath: upload_snapshot.sh
            - mountPath: /data
              name: snapshot-volume-partition
            - mountPath: /secret
              name: aws-keys
              readOnly: true
            env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: token
            - name: CF_DISTRIBUTION_ID
              valueFrom:
                secretKeyRef:
                  name: aws-keys
                  key: cf_distribution_id
          initContainers:
          - args:
            - 100291/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCA3lzUAt0QBfG.+ezw4CQ69zBy669sANEt5juSJgzqcgIgbozfpcyeuKJDeJoT5exyGYDYBqCpxklsMEfs0SQ6qzo=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTcyOmh0dHBzOi8vcmVsZWFzZS5uaW5lLWNocm9uaWNsZXMuY29tL21haW4vdjEwMDI5MS9sYXVuY2hlci92MS9XaW5kb3dzLnppcHU5OnRpbWVzdGFtcHUxMDoyMDIyLTA5LTA3ZQ==
            - $(SLACK_TOKEN)
            command:
            - /bin/preload_headless.sh
            image: planetariumhq/ninechronicles-headless:v100291
            name: preload-headless
            volumeMounts:
            - mountPath: /bin/preload_headless.sh
              name: snapshot-script-partition
              readOnly: true
              subPath: preload_headless.sh
            - mountPath: /data
              name: snapshot-volume-partition
            - mountPath: /secret
              name: aws-keys
              readOnly: true
            env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: token
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: 9c-main-4xl
            beta.kubernetes.io/os: linux
          restartPolicy: Never
          volumes:
          - configMap:
              defaultMode: 448
              name: snapshot-script-partition
            name: snapshot-script-partition
          - name: snapshot-volume-partition
            persistentVolumeClaim:
              claimName: snapshot-volume-partition
          - name: aws-keys
            secret:
              secretName: aws-keys
  schedule: 0 */3 * * *
  successfulJobsHistoryLimit: 1
