apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main-tcp-seed-3
  name: main-tcp-seed-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-tcp-seed-3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: main-tcp-seed-3
    spec:
      containers:
      - args:
        - Libplanet.Seed.Executable.dll
        - run
        - --log-level=debug
        - --app-protocol-version=100291/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCA3lzUAt0QBfG.+ezw4CQ69zBy669sANEt5juSJgzqcgIgbozfpcyeuKJDeJoT5exyGYDYBqCpxklsMEfs0SQ6qzo=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTcyOmh0dHBzOi8vcmVsZWFzZS5uaW5lLWNocm9uaWNsZXMuY29tL21haW4vdjEwMDI5MS9sYXVuY2hlci92MS9XaW5kb3dzLnppcHU5OnRpbWVzdGFtcHUxMDoyMDIyLTA5LTA3ZQ==
        - --host=9c-main-tcp-seed-3.planetarium.dev
        - --port=31234
        - --private-key=$(SEED_PRIVATE_KEY)
        - --graphql-host=0.0.0.0
        - --graphql-port=31237
        - --workers=500
        command:
        - dotnet
        image: planetariumhq/libplanet-seed:git-4d10b228048c03cc97a6fbb7fbfcd54d2bd1b21c
        imagePullPolicy: IfNotPresent
        env:
        - name: SEED_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: seed3
              name: seed-keys
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 31234
          timeoutSeconds: 1
        name: main-tcp-seed-3
        ports:
        - containerPort: 31234
          name: node
          protocol: TCP
        - containerPort: 31237
          name: graphql
          protocol: TCP
        resources:
          requests:
            cpu: '1'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: 9c-main-2xl
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
