name: release
on:
  push:
    tags: ["v*-rc*", "test-v*-rc*"]

jobs:
  release-internal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - uses: actions/setup-dotnet@v2
        with:
          python-version: 3.9
          dotnet-version: '3.1.x'
      - run:
          dotnet tool install -g Libplanet.Tools
      - run: 
          python -m pip install -r requirements.txt
        working-directory: py-scripts
        name: install dependencies
      - run:
          planet key import --passphrase ${{ secrets.INTERNAL_PASSPHRASE }} ${{ secrets.INTERNAL_PRIVATE_KEY }}
      - run: |
          python cli.py release internal $GITHUB_REF_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.M_GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACk_TOKEN }}
          INTERNAL_PASSPHRASE: ${{ secrets.INTERNAL_PASSPHRASE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: py-scripts
